### ISSUE TITLE
Do something about the missing repos

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-repo-data#134]
`origami-repo-data` only includes repos that have (or once had) an `origami.json`, we have [quite](https://github.com/Financial-Times/polyfill-library-node) a [few](https://github.com/Financial-Times/oax/) that [don't](https://github.com/Financial-Times/polyfill-service-url-builder).

I've seen some repos that have an `origami.json` with an `origamiType` of `null`, but this is illegal [according to the spec](https://origami.ft.com/spec/v1/manifest/#origamitype).

What should we do? Should we add a new enumeral to `origamiType` to cover these, and then add `origami.json` to the rest of the repos?

Figure out what repos are Origami-owned another way?
Figure out what repos are Origami-owned another way? such as the who owns the

**Comment by rowanmanning** [comment]
Yep we originally added `origami.json` to all of the repos, it _is_ against-spec to use `null` but we found some that _did_ have a type of `null` and the previous version of the registry treated these as "not a component or service". I think making this part of the spec is probably the quickest way of getting everything into repo data.

**Comment by chee** [comment]
Do you think we should use `null`?

Or create a new value (or new values) that describe these things such as `tool` so that we can describe what they are?

Related: https://github.com/Financial-Times/origami-repo-data/issues/134

**Comment by rowanmanning** [comment]
I think we always need to support `null` for "this is owned by Origami but can't be categorised". Back when we rebuilt the registry we did talk about introducing another type (or types) but I think the outcome was "let's just get this built and replicate the existing registry for now".

The difficulty with adding more types _might_ be if something fits into multiple types? Like if something is both a node module and a command-line tool. Also now that components are available via npm, there's maybe an issue with having a type of `module` anyway.

Oh yeah that reminds me, we also were struggling to work out what types should be because we have this annoying legacy of using `module` when we mean `component` 😩

**Comment by chee** [comment]
Do we have documented anywhere what `service`, `module` and `imageset` mean?

**Comment by chee** [comment]
Things with null:

```
build-tools
bundle-size-cli
eslint-config-origami-component
express-web-service
ftheadshots
get-github-public-organisation-repositories
github-label-sync
grafana-tools
image-set-tools
navigation-data
node-health-check
proposals
react
release-log
repo-data-client-node
service-makefile
service
source-param-middleware
streamcat
svg-tint-stream
```

**Comment by rowanmanning** [comment]
> Do we have documented anywhere what service, module and imageset mean?
I don't think we do. I can outline what they mean based on what has those now, this is _my_ understanding but it's not necessarily shared.

`service` is something we build that is available over HTTP and serves requests. It follows the [Service Specification](https://origami.ft.com/spec/v1/services/). This definition covers everything we currently run. They all have ongoing costs associated with them because they are always running (or always have a number of requests being made to them).

`module` is a front-end component. It follows the [Component Specification](https://origami.ft.com/spec/v1/components/).

`imageset` is a suite of images that can be used with the Origami Image Service, aliased via a custom scheme.

**Comment by chee** [comment]
the origami component spec says that components *must* contain an `origami.json` with a `type` ([which i think is a bug?](https://github.com/Financial-Times/origami/pull/147)) of `module`.
The services spec doesn't mention the `origamiType` or `type`.

I think adding an `origamiType` of `tool` or something similar would be good. 

I think we could even expand to adding `tool`, `library`, `website`, `config`, `example`/`template` and `meta`. And add descriptions of what each of these mean to the spec too. 

I don't think it will cause any problems because it [looks like](https://github.com/search?l=JavaScript&q=origamiType+org%3Afinancial-times&type=Code) the only thing to pay attention to the `origamiType` is the `build-tools` which won't be run on any of these repos.

I also don't see any definition of what the `categoryType` values of `components`, `primitives`, `utilities` and `layouts` mean in the spec :3

**Comment by chee** [comment]
> > Do we have documented anywhere what service, module and imageset mean?
> 
> I don't think we do. I can outline what they mean based on what has those now, this is _my_ understanding but it's not necessarily shared.
> 
>     * `service` is something we build that is available over HTTP and serves requests. It follows the [Service Specification](https://origami.ft.com/spec/v1/services/). This definition covers everything we currently run. They all have ongoing costs associated with them because they are always running (or always have a number of requests being made to them).
> 
>     * `module` is a front-end component. It follows the [Component Specification](https://origami.ft.com/spec/v1/components/).
> 
>     * `imageset` is a suite of images that can be used with the Origami Image Service, aliased via a custom scheme.

Thanks! We should add something like this to the spec!!

 `module` meaning front-end component means we need another word for libraries and tools

**Comment by rowanmanning** [comment]
I'm up for adding more types, sounds like a proposal. In the meantime should we allow `null` as historically we need to support it? Like `null` is allowed but a specified `type` is preferred?

For some reason Repo Data doesn't come up in that search. It also uses `origamiType` and there are interface differences in the registry which change depending on it. https://github.com/Financial-Times/origami-repo-data/search?q=origamiType&unscoped_q=origamiType - We save it as `type` in the database though.

> the origami component spec says that components must contain an origami.json with a type (which i think is a bug?) of module.
Yep it's a bug I think.

**Comment by chee** [comment]
@rowanmanning ah, i bet it's because repo-data changes the field to `type` on `version`. So i'll need to look at uses of `type` on data from `repo-data` too:)

**Comment by chee** [comment]
@rowanmanning i'll file a PR to the spec, then to the manifest schema, then write a proposal ^_^

**Comment by chee** [comment]
I've filed this proposal now: https://github.com/Financial-Times/origami/issues/156

**Comment by chee** [comment]
I'm going to add an issue to the `origami`  repo for to add `origami.json` to more repos, and assign myself and work on that. So this repo can be closed, I'll link to this comment from the new issue.
